### ISSUE TITLE
To make code more readable, use import PySimpleGUI as sg

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [wrongsyntax/Comp-Sci-20#1]
If you modify your import statement to be
`import PySimpleGUI as sg`

Then instead of writing this:
`PySimpleGUI.Button('C'), `

You will write:
`sg.Button('C'), `

**Comment by wrongsyntax** [comment]
Fixed. Just wondering, is there a way to increase the text size of buttons?

**Comment by MikeTheWatchGuy** [comment]
You'll find the docs are really informative and easy to follow:
http://www.PySimpleGUI.org

To change the font/size of Element (Text, button, input, etc), you use the `font` parameter.  You'll find the format explained in the docs and maybe the Cookbook too, I don't recall exactly.

**Comment by wrongsyntax** [comment]
Yes, I've tried using the font parameter, it only made the size of the button bigger, not the button text itself. Thanks anyway.

**Comment by MikeTheWatchGuy** [comment]
Here's how to do it
https://repl.it/@PySimpleGUI/Button-Text-Size

**Comment by wrongsyntax** [comment]
This only seems to work when the `default_button_element_size` parameter is not in use.

**Comment by wrongsyntax** [comment]
It only seems to do this on my program, weird.
